name: ptsp_tipulu_ap
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  url_launcher: ^6.3.2
  dio: ^5.9.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  share_plus: ^12.0.0
  flutter_pdfview: ^1.4.3
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  # ✅ Sinkronkan semua WebView ke versi terbaru yang support getCookies()
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.23.1
  image_picker: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # Ikon utama untuk iOS dan Android versi lama
  
  # Konfigurasi khusus untuk ikon adaptif di Android
  adaptive_icon_background: "#FFFFFF" # <-- Ganti dengan warna background Anda
  adaptive_icon_foreground: "assets/images/logo.png" # <-- Path ke logo transparan

flutter:
  uses-material-design: true
  assets:
    - assets/images/
