// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLwI4qDJKoK4QI5T4LiZSOYsj7Grx9Pg',
    appId: '1:678173948467:web:66b37a2878bb9fe77fc146',
    messagingSenderId: '678173948467',
    projectId: 'ptsp-kelurahan-tipulu',
    authDomain: 'ptsp-kelurahan-tipulu.firebaseapp.com',
    databaseURL: 'https://ptsp-kelurahan-tipulu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ptsp-kelurahan-tipulu.firebasestorage.app',
    measurementId: 'G-Z3Y04KZ5BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpesG7YboHYxwdEDIQGp7FELFc2EwZkkI',
    appId: '1:678173948467:android:f8bab7c78df63a287fc146',
    messagingSenderId: '678173948467',
    projectId: 'ptsp-kelurahan-tipulu',
    databaseURL: 'https://ptsp-kelurahan-tipulu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ptsp-kelurahan-tipulu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkHv66pxaIlFcNNEwHTggQLCV88YdE-TE',
    appId: '1:678173948467:ios:d550b959d4dd1bfa7fc146',
    messagingSenderId: '678173948467',
    projectId: 'ptsp-kelurahan-tipulu',
    databaseURL: 'https://ptsp-kelurahan-tipulu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ptsp-kelurahan-tipulu.firebasestorage.app',
    iosBundleId: 'com.example.ptspTipuluApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkHv66pxaIlFcNNEwHTggQLCV88YdE-TE',
    appId: '1:678173948467:ios:d550b959d4dd1bfa7fc146',
    messagingSenderId: '678173948467',
    projectId: 'ptsp-kelurahan-tipulu',
    databaseURL: 'https://ptsp-kelurahan-tipulu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ptsp-kelurahan-tipulu.firebasestorage.app',
    iosBundleId: 'com.example.ptspTipuluApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwLwI4qDJKoK4QI5T4LiZSOYsj7Grx9Pg',
    appId: '1:678173948467:web:d3c1d21bfa1112de7fc146',
    messagingSenderId: '678173948467',
    projectId: 'ptsp-kelurahan-tipulu',
    authDomain: 'ptsp-kelurahan-tipulu.firebaseapp.com',
    databaseURL: 'https://ptsp-kelurahan-tipulu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ptsp-kelurahan-tipulu.firebasestorage.app',
    measurementId: 'G-EFBP79FWWW',
  );
}
